package net.feminaexlux.converter.clubschedulertoexcel.organization;

public enum Role {

	OPENING_THOUGHT,
	TOASTMASTER,
	TIMER,
	AH_COUNTER,
	GRAMMARIAN,
	LEADERSHIP_MANUAL_EVALUATOR,
	SPEAKER_1,
	SPEAKER_2,
	SPEAKER_3,
	TABLE_TOPICS_MASTER,
	GENERAL_EVALUATOR,
	EVALUATOR_1,
	EVALUATOR_2,
	EVALUATOR_3

}
